services:
  db:
    image: postgres:latest
    container_name: cube_rollup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pipeline:
    container_name: pipeline
    image: viz_pipeline:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
      - "8501:8501"  # Streamlit UI

    user: "${UID}:${GID}"
    environment:
      - AIRFLOW_UID=${UID}
    command: >
      bash -c "
      mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins /opt/airflow/scripts &&
      chmod -R 777 /opt/airflow &&
      airflow standalone
      "